# Generated by Django 6.0.4 on 2026-05-31 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srmsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectcombination',
            name='student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srmsapp.class'),
        ),
    ]
